apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.apps.Env }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
    module: {{ .Values.tier }}
    env: {{ .Values.apps.Env }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
