name: Go-App Deployment Workflow

on:
  workflow_dispatch: 

env:
  NAMESPACE: go-app
  RELEASE_NAME: go-app
  IMAGE_TAG: "${{ github.run_number }}"
  DOCKERHUB_NAME: chanuts/devops-assignment
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t {{ env.DOCKERHUB_NAME}}:{{ env.IMAGE_TAG }} .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push {{ env.DOCKERHUB_NAME }}:{{ env.IMAGE_TAG }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'helm'

      - name: Deploy Docker Image using Helm
        run: |
          helm upgrade --install --create-namespace release-name ./go-app/ \
            --set releaseName=${{ env.RELEASE_NAME }} \
            --set namespace=${{ env.NAMESPACE }}
